[package]
name = "maze-wasm"
version = "0.1.0"
authors = ["Thomas Feldmann <mail@tfeldmann.de>"]
description = "A WASM maze generator."
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
